version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: yardsales_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
